### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by Aryan9592**
## Overview
This PR fixes some typos or grammatical mistakes!

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

## Summary by CodeRabbit

Documentation:
- Corrected a typo in the comments of the `Blobstream` contract, improving readability.
- Clarified the structure of the Merkle tree in the comments, enhancing understanding of the data structure. 

Please note that these changes are purely documentation updates and do not affect the functionality of the system.

### CODE REVIEW

**Comment by Aryan9592** [comment]
For sure man!

**Review by SweeXordious — DISMISSED** [review]

**Review by evan-forbes — DISMISSED** [review]

**Review by adlerjohn — DISMISSED** [review]

**Comment by Aryan9592** [comment]
hmm just saw it..But how to re-generate that go-wrapper?

**Comment by adlerjohn** [comment]
@Aryan9592 https://github.com/celestiaorg/blobstream-contracts#regenerate-go-wrappers

**Comment by Aryan9592** [comment]
Screenshot (67)

Seems fine right?

**Comment by SweeXordious** [comment]
@Aryan9592 did you run `make`? If so, add those changes, then push them to this branch.

**Comment by Aryan9592** [comment]
yea I ran that `make` command. But it doesn't really modified any file. Guess it better to just push it

**Review by SweeXordious — APPROVED** [review]

**Pull request merged**
